---
# tasks file for apigee-opdk-settings-ldap
- name: Normalized ldap attributes
  cache:
    key: '{{ item.key }}'
    value: '{{ item.value }}'
  with_items:
  - { key: 'opdk_ldap_type', value: '1' }
  - { key: 'opdk_ldap_port', value: '{{ opdk_ldap_port }}' }

- name: Normalized name for ldap ip if on dc-1
  cache:
    key: 'opdk_ldap_ip'
    value: "{{ hostvars[groups['dc-1-ms'][0]]['private_address'] }}"
  when: groups['dc-1'] is defined and groups['dc-1-ms'] is defined and groups['dc-1-ldap'] is not defined and inventory_hostname in groups['dc-1'] and hostvars[groups['dc-1-ms'][0]][interface_name].ipv4.address is defined

- block:
  - name: Normalized name for ldap ip when ldap is a declared if on dc-1
    cache:
      key: '{{ item.key }}'
      value: "{{ item.value }}"
    with_items:
    - { key: 'opdk_ldap_ip', value: "{{ hostvars[groups['dc-1-ldap'][0]]['private_address'] }}" }
    - { key: 'opdk_ldap_sid', value: '1' }

  - name: Set ldap remote flag
    cache:
      key: 'use_opdk_ldap_remote_host'
      value: 'y'
    when: opdk_ldap_ip != local_mgmt_ip

  - name: Set ldap type
    cache:
      key: 'opdk_ldap_type'
      value: '2'
    when: groups['dc-2-ldap'] is defined

  when: groups['dc-1'] is defined and groups['dc-1-ldap'] is defined and inventory_hostname in groups['dc-1'] and hostvars[groups['dc-1-ms'][0]]['private_address'] is defined

- name: Normalized name for ldap ip if on dc-2
  cache:
    key: 'opdk_ldap_ip'
    value: "{{ hostvars[groups['dc-2-ms'][0]]['private_address'] }}"
  when: groups['dc-2'] is defined and groups['dc-2-ms'] is defined and groups['dc-2-ldap'] is not defined and inventory_hostname in groups['dc-2'] and hostvars[groups['dc-2-ms'][0]]['private_address'] is defined

- block:
  - name: Normalized name for ldap ip is declared if on dc-2
    cache:
      key: '{{ item.key }}'
      value: "{{ item.value }}"
    with_items:
    - { key: 'opdk_ldap_ip', value: "{{ hostvars[groups['dc-2-ldap'][0]]['private_address'] }}" }
    - { key: 'opdk_ldap_sid', value: '2' }

  - name: Set ldap remote flag
    cache:
      key: 'use_opdk_ldap_remote_host'
      value: 'y'
    when: opdk_ldap_ip != local_mgmt_ip

  - name: Set ldap type
    cache:
      key: 'opdk_ldap_type'
      value: '2'
    when: groups['dc-1-ldap'] is defined

  when: groups['dc-2'] is defined and groups['dc-2-ldap'] is defined and inventory_hostname in groups['dc-2'] and hostvars[groups['dc-1-ms'][0]]['private_address'] is defined

- name: Normalized name for management server local ip to dc-1 if current node is not on dc-1 or dc-2
  cache:
    key: 'opdk_ldap_ip'
    value: "{{ local_mgmt_ip }}"
  when: opdk_ldap_ip is not defined or opdk_ldap_ip | trim | length == 0

